---

- name: "Install nginx repository"
  yum_repository:
    name: "nginx-{{ nginx_branch }}"
    description: "nginx {{ nginx_branch }} repository"
    baseurl: "{{ nginx_repo }}"
    gpgcheck: true
    gpgkey: "https://nginx.org/keys/nginx_signing.key"
    enabled: true
    state: "present"

- name: "Install nginx package"
  yum:
    name: "nginx-{{ nginx_version }}"
    state: "present"
