---

- name: "Install nginx repository"
  yum_repository:
    name: "nginx-{{ nginx_branch }}"
    description: "nginx {{ nginx_branch }} repository"
    baseurl: "{{ nginx_repo }}"
    gpgcheck: true
    gpgkey: "https://nginx.org/keys/nginx_signing.key"
    enabled: true
    state: "present"

- name: "Install nginx package"
  yum:
    name: "nginx-{{ nginx_version }}"
    state: "present"
- name: Enable and start nginx
  systemd:
    name: nginx
    enabled: true
    state: started
  when: nginx_start

- name: Disable and stop nginx
  systemd:
    name: nginx
    enabled: true
    state: started
  when: not nginx_start

- name: "Copy main nginx config"
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: "Download upstreams config"
  get_url:
    url: "{{ nginx_upstreams_url }}"
    dest: "/tmp/nginx_upstreams.yml"
    force: true
  register: "nginx_upstreams_download_result"

- name: "Read upstreams config"
  slurp:
    src: "/tmp/nginx_upstreams.yml"
  register: slurp_upstreams

- name: Debug
  debug:
    msg: "{{ slurp_upstreams['content'] | b64decode | from_yaml }}"

- name: "Generate nginx upstreams config"
  template:
    src: conf.d/upstreams.conf.j2
    dest: /etc/nginx/conf.d/upstreams.conf
